-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 10:20:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_FARMACIA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_FARMACIA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_FARMACIA` DEFAULT CHARACTER SET utf8 ;
USE `DB_FARMACIA` ;

-- -----------------------------------------------------
-- Table `DB_FARMACIA`.`TB_CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_FARMACIA`.`TB_CATEGORIA` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `Medicamentos` VARCHAR(255) NOT NULL,
  `Cuidados diarios` VARCHAR(255) NOT NULL,
  `Suplementos alimentares` VARCHAR(255) NOT NULL,
  `Promoções` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_FARMACIA`.`TB_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_FARMACIA`.`TB_PRODUTO` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `decricao` VARCHAR(255) NOT NULL,
  `preco` DECIMAL NOT NULL,
  `fabricante` VARCHAR(255) NOT NULL,
  `quantidade` BIGINT(5) NOT NULL,
  `categoria` VARCHAR(255) NOT NULL,
  `TB_CATEGORIA_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `TB_CATEGORIA_id`),
  INDEX `fk_TB_PRODUTO_TB_CATEGORIA_idx` (`TB_CATEGORIA_id` ASC) VISIBLE,
  CONSTRAINT `fk_TB_PRODUTO_TB_CATEGORIA`
    FOREIGN KEY (`TB_CATEGORIA_id`)
    REFERENCES `DB_FARMACIA`.`TB_CATEGORIA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
